server:
  port: 8989

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: SmartSpace

  datasource:
    url: "jdbc:mysql://localhost:3306/smart_space?createDatabaseIfNotExist=true"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        type:
          json_format_mapper: com.vn.smart_space.configuration.CustomHibernateJsonFormatter

  # Redis Config
  data:
    redis:
      host: localhost
      port: 6379

  # Mail Config (Gmail SMTP)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Config
jwt:
  signerKey: ${JWT_SIGNER_KEY}

# Google OAuth2
google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI}

# Cloudinary Config
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder: smartspace

firebase:
  service-account-path: classpath:smart-space-36687-firebase-adminsdk-fbsvc-5c08d9199a.json
